
name: Terraform Plan

on:
   pull_request_target:
    branches:
      - dev
    paths:
      - 'infra_code/env/dev/*'
      - 'infra_code/env/dev/*.tf'
      - 'infra_code/modules/**/*.tf'

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: infra_code/env/dev/
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::851687812387:role/github-actions-terraform-plan-role-dev-acc
          role-session-name: GitHubActions-TerraformPlan
          aws-region: ap-south-1
  
      - name: Installing Terraform 
        uses: hashicorp/setup-terraform@v3
        with: 
          terraform_version: "1.14.3"
            
      - name: Terraform Init
        run: |
          terraform init

      - name: Terraform fmt
        run: | 
          terraform fmt
          
      - name: Terraform Force Unlock (if stuck)
        run: |
          terraform force-unlock -force 2ca4c4bb-9673-0f44-b470-c80e7a7d5a5a


      - name: Terraform Validate
        run: | 
          terraform validate
          

      - name: Terraform Plan
        run: |
          terraform plan -var-file=dev.tfvars
     
